services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network
    ports:
      - "5432:5432"
  
  python:
    build:
      context: ./python
    container_name: python_app
    restart: "no"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network

  jupyter:
    build:
      context: ./jupyter
    container_name: jupyter_notebook
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter:/home/jovyan/work
    networks:
      - app_network
    command: >
      start-notebook.py
      --NotebookApp.token=''
      --NotebookApp.password=''

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge